Sprint 13
LobovVit/ImageFeed pull request #6
Opened 2024-12-16 18:59 UTC by LobovVit

Sprint 13

2024-12-17 07:36 UTC, NaR0RoW requested changes

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeed/Alert/AlertModel.swift
> +//  Alert.swift
Не соответствует названию файла

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeed/Alert/AlertModel.swift
> +    var secondButtonText: String? = nil
Можно не присваивать `nil`

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeed/Auth/AuthConfiguration.swift
> +import Foundation
Не хватает переноса строки

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeed/Auth/AuthHelper.swift
> +import Foundation
Лучше отделять импорты от заголовка файла. Проверь пожалуйста это во всем коде

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeed/Auth/AuthHelper.swift
> +    func code(url: URL) -> String?
В общем случае функция предполагает выполнение определенного действия, поэтому название этих методов можно немного улучшить, например:
`func createAuthRequest() -> URLRequest?`
Хотя в данном случае я бы воспользовался вычисляемой переменной:
```
var authRequest: URLRequest? {
   guard let url = authURL() else { return nil}
   return URLRequest(url: url)
}
```

Для второго метода, что-то вроде:
`func getCode(for url: URL) -> String?`

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeed/Auth/AuthHelper.swift
> +    let configuration: AuthConfiguration
Поле можно сделать приватным

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeed/Auth/AuthHelper.swift
> +    func authURL() -> URL? {
Лучше сделать вычисляемой переменной или изменить название метода на `createAuthURL() -> URL?`

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeed/Auth/AuthHelper.swift
> +    func authURL() -> URL? {
Для достижения [инкапсуляции](https://habr.com/ru/articles/87205/) лучше пометить это поля `private`.
Перепроверь все свойства и методы в классах. Они должны быть максимально инкапсулированы и скрыты внутри класса

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeed/Auth/AuthHelper.swift
> +            urlComponents.path ==  Constants.authorizeNative ,
Лишний пробел перед запятой в конце

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeed/Profile/ProfileViewController.swift
> +class ProfileViewController: UIViewController, ProfileViewControllerProtocol {
Давай проставлять ключевое слово `final` классам для ускорения работы компилятора.

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeed/Profile/ProfileViewController.swift
> +    internal func updateAvatar() {
Внутренний уровень стоит по умолчанию для свойств и методов и предоставляет доступ внутри модуля. Явно указывать internal не нужно

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeedTests/ImagesListTests/ImagesListViewControllerSpy.swift
> +    var tableViewUpdatesCalled: Bool =  false
Лишний пробел после знака равно

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeedUITests/ImageFeedUITests.swift
> +class Image_FeedUITests: XCTestCase {
Не хватает `final`

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeedUITests/ImageFeedUITests.swift
> +    private enum const {
Название `enum` должно начинаться с большой буквы

2024-12-17 07:36 UTC, NaR0RoW commented on ImageFeedUITests/ImageFeedUITests.swift
Комментарии можно убрать

2024-12-17 09:39 UTC, LobovVit commented on ImageFeed/Alert/AlertModel.swift
> +//  Alert.swift
Подправил

2024-12-17 09:40 UTC, LobovVit commented on ImageFeed/Alert/AlertModel.swift
> +    var secondButtonText: String? = nil
Подправил

2024-12-17 09:40 UTC, LobovVit commented on ImageFeed/Auth/AuthConfiguration.swift
> +import Foundation
Подправил

2024-12-17 09:42 UTC, LobovVit commented on ImageFeed/Auth/AuthHelper.swift
> +import Foundation
Подправил

2024-12-17 09:46 UTC, LobovVit commented on ImageFeed/Auth/AuthHelper.swift
> +    func code(url: URL) -> String?
Подправил

2024-12-17 09:48 UTC, LobovVit commented on ImageFeed/Profile/ProfileViewController.swift
> +    internal func updateAvatar() {
Подправил

2024-12-17 09:48 UTC, LobovVit commented on ImageFeedTests/ImagesListTests/ImagesListViewControllerSpy.swift
> +    var tableViewUpdatesCalled: Bool =  false
Подправил

2024-12-17 09:48 UTC, LobovVit commented on ImageFeedUITests/ImageFeedUITests.swift
> +class Image_FeedUITests: XCTestCase {
Подправил

2024-12-17 09:49 UTC, LobovVit commented on ImageFeedUITests/ImageFeedUITests.swift
> +    private enum const {
Подправил

2024-12-17 09:49 UTC, LobovVit commented on ImageFeed/Auth/AuthHelper.swift
> +    let configuration: AuthConfiguration
Подправил

2024-12-17 09:50 UTC, LobovVit commented on ImageFeed/Auth/AuthHelper.swift
> +    func authURL() -> URL? {
Подправил

2024-12-17 09:51 UTC, LobovVit commented on ImageFeed/Auth/AuthHelper.swift
> +    func authURL() -> URL? {
Подправил

2024-12-17 09:52 UTC, LobovVit commented on ImageFeed/Auth/AuthHelper.swift
> +            urlComponents.path ==  Constants.authorizeNative ,
Подправил

2024-12-17 19:26 UTC, NaR0RoW approved these changes
По коду все хорошо, отличная работа! Теперь нужно поправить тесты.

Еще такой момент: если поправил мой комментарий в пул реквесте, то достаточно нажать кнопку `Resolve conversation`. А вот если остались вопросы или мой комментарий не получается исправить, то кнопку `Resolve conversation` нажимать не нужно и стоит написать свой комментарий в треде

2024-12-19 15:24 UTC, NaR0RoW commented on ImageFeed/Images/ImagesListCell.swift
> +        likeButton.accessibilityIdentifier = "LikeButton"
У нас ведь уже есть `accessibilityIdentifier` у `LikeButton`, поставленный в `Main Storyboard`

2024-12-19 15:24 UTC, NaR0RoW commented on ImageFeedUITests/ImageFeedUITests.swift
> +        cell.swipeUp()
Тут стоит ждать, пока `cell` появится на экране. У нас ведь `Splash Screen` до этого показывается

2024-12-19 15:24 UTC, NaR0RoW commented on ImageFeedUITests/ImageFeedUITests.swift
> +        let cellToLike = tablesQuery.children(matching: .cell).element(boundBy: 1)
Мы делаем свайп и пытаемся нажать на лайк, который не видно на экране. У меня тест все равно падает на этом моменте

2024-12-19 15:29 UTC, NaR0RoW commented
Видео на две части обрезал, т.к. гитхаб не позволяет больше 10 МБ за раз загрузить

https://github.com/user-attachments/assets/5b259659-9f6c-4439-95a6-ff753c2d78e2

https://github.com/user-attachments/assets/b3cce74a-34d9-4fc3-afea-b4e2b5ac6d45

2024-12-19 15:50 UTC, LobovVit commented
у меня такое поведение при медленной сети 
если все ОК с новым ключом и без rate limit от Unsplash - https://disk.yandex.ru/i/QHhVUqr0quZD2g

пробовал проверять на isHittable по сути все элементы и кнопку и ячейку - и крутил в цикле от первого до 5-го элемента  -  ошибка у меня вылетает периодически (если смотреть на тест - то вылетает когда ProgressHUD крутится долго - дольше тайм-аутов ожидания)

2024-12-19 18:01 UTC, NaR0RoW commented
С сетью у меня проблем нет, разве что с сервисом могут быть проблемы

<img width="1069" alt="Screenshot 2024-12-19 at 19 38 36" src="https://github.com/user-attachments/assets/fd3e0dda-fb98-4f7d-8a20-03d30c55d31d" />

Вот тут например видно, `ProgressHUD` прокрутился достаточно быстро, но тест все равно упал

https://github.com/user-attachments/assets/a8f1bde4-7cf1-4ff8-915b-be9455c23b70

2024-12-19 18:05 UTC, NaR0RoW commented
И такое поведение всегда повторяется. На 11 айфоне тоже. Xcode 16.2 iOS 18.2

2024-12-20 10:25 UTC, NaR0RoW commented
https://github.com/user-attachments/assets/399532c3-cda5-465c-953c-6734a07b9ba7

https://github.com/user-attachments/assets/eec1eaf6-08a2-44ff-94de-b73339619178

2024-12-20 10:27 UTC, NaR0RoW commented
https://github.com/user-attachments/assets/6e061178-7b6c-420f-8176-2ad8abd34833


https://github.com/user-attachments/assets/0a0f2395-8605-4b10-9f75-7bb9df1dc89c


https://github.com/user-attachments/assets/245af004-3c7d-47e1-b197-25c0a3c00582

2024-12-20 10:52 UTC, NaR0RoW commented
Привет!
К сожалению, все еще не могу принять твою работу, так как тест у меня всегда падает. Обратись пожалуйста к наставнику за помощью.

2024-12-21 12:00 UTC, NaR0RoW approved these changes
Теперь все работает как нужно, отличная работа 🔥

2024-12-21 12:12 UTC, merged